database:
  # NOTE: By design, this setting prevents the SQLITE_DATABASE environment variable
  # from affecting test runs, so that we don't accidentally affect the
  # production database during testing. If you're not concerned about that and
  # would like to have environment variable overrides, you could instead use
  # something like:
  #
  #   database: "_env:SQLITE_DATABASE:crud-ex-backend-yesod_test.sqlite3"
  database: crud-ex-backend-yesod_test.sqlite3

auth-dummy-login: true

elmAppSettings:
   logConfig:
      on: true
      logUpdateOn: true
      logViewOn: false
      logInitOn: true
      logNavOn: true
      logNavLocOn: true
      logMsgOn: true
      logModelOn: false
      logInputOn: true
      logOutputOn: true
      logHtmlOn: false
      logSubOn: false
      logFlagsOn: true
   layout : "TEST0"
